branches:
  only:
    - master
sudo: enabled
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential
  - sudo apt-get install -qq scons
  - sudo apt-get install -qq python-dev
  - sudo apt-get install -qq swig
  - sudo apt-get install -qq libprotobuf-dev python-protobuf protobuf-compiler libgoogle-perftools-dev
  - sudo apt-get install -qq m4
install: true
script: cd gem5; echo | scons build/X86/gem5.fast -j3
